[package]
name = "globus-identity"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
argon2 = "0.5"
bip39 = { version = "2.1", features = ["rand"] }
hmac = "0.12"
sha2 = "0.10"
zeroize = { version = "1", features = ["zeroize_derive"] }

[lints]
workspace = true
