[package]
name = "globus-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
[lints]
workspace = true

[dependencies]
aurora-core = { path = "../aurora-core" }
globus-system-core = { path = "../core" }
globus-services = { path = "../services" }
globus-vfs = { path = "../vfs" }
globus-net = { path = "../net" }
globus-devices = { path = "../devices" }
globus-graphics = { path = "../graphics" }
globus-audio = { path = "../audio" }
globus-package = { path = "../package" }
globus-update = { path = "../update" }
globus-identity = { path = "../identity" }
globus-wallet-service = { path = "../wallet-service" }
globus-diagnostics = { path = "../diagnostics" }
libshivacore = { path = "../shivacore-api" }

shivacore-service-space = { path = "../../modules/atc-shivacore/service_space" }
