// Copyright (c) 2026 Michael Wroblewski / ShivaCore / A-TownChain-Okosystems. All Rights Reserved.
// K-Sprint 20 — Contract-Call-Integration
use alloc::format;
use alloc::vec;
use alloc::vec::Vec; use alloc::string::{String,ToString}; use alloc::sync::Arc;
use crate::mempool::{Transaction,TxType};
use crate::vm::{VmEngine,ExecResult,VmError};
use crate::security::simple_hash;
pub struct ContractExecutor{vm:Arc<VmEngine>,state:Arc<crate::mempool::StateDb>}
impl ContractExecutor{pub fn new(vm:Arc<VmEngine>,state:Arc<crate::mempool::StateDb>)->Self{ContractExecutor{vm,state}}
pub fn process_deploy(&self,tx:&Transaction)->Result<String,ContractError>{if tx.tx_type!=TxType::ContractDeploy{return Err(ContractError::WrongTxType);}if tx.payload.len()<4{return Err(ContractError::InvalidPayload("too short".into()));}let bl=u32::from_be_bytes([tx.payload[0],tx.payload[1],tx.payload[2],tx.payload[3]]) as usize;if tx.payload.len()<4+bl{return Err(ContractError::InvalidPayload("length mismatch".into()));}let bytecode=tx.payload[4..4+bl].to_vec();let mut ai=Vec::new();ai.extend_from_slice(tx.sender_did.as_bytes());ai.extend_from_slice(&tx.nonce.to_be_bytes());ai.extend_from_slice(&tx.poh_hash);let ah=simple_hash(&ai);let addr=format!("did:contract:{}",hex(&ah[..8]));self.vm.deploy(addr.clone(),bytecode.clone(),tx.sender_did.clone());let r=self.vm.call(&addr,tx.sender_did.clone(),Some(tx.gas_limit));if!r.success{return Err(ContractError::ExecutionFailed(format!("{:?}",r)));}Ok(addr)}
pub fn process_call(&self,tx:&Transaction)->Result<ExecResult,ContractError>{if tx.tx_type!=TxType::ContractCall{return Err(ContractError::WrongTxType);}if tx.payload.len()<2{return Err(ContractError::InvalidPayload("too short".into()));}let al=u16::from_be_bytes([tx.payload[0],tx.payload[1]]) as usize;if tx.payload.len()<2+al{return Err(ContractError::InvalidPayload("addr mismatch".into()));}let addr=String::from_utf8_lossy(&tx.payload[2..2+al]).to_string();if!self.vm.registry.exists(&addr){return Err(ContractError::ContractNotFound(addr));}let r=self.vm.call(&addr,tx.sender_did.clone(),Some(tx.gas_limit));if!r.success{return Err(ContractError::ExecutionFailed(format!("{:?}", r)));}Ok(r)}
pub fn process_tx(&self,tx:&Transaction)->Result<TxProcessingResult,ContractError>{match tx.tx_type{TxType::ContractDeploy=>{let a=self.process_deploy(tx)?;Ok(TxProcessingResult::Deployed(a))}TxType::ContractCall=>{let r=self.process_call(tx)?;Ok(TxProcessingResult::Called(r))}_=>Err(ContractError::NotAContractTx)}}pub fn vm(&self)->&Arc<VmEngine>{&self.vm}}
#[derive(Debug,Clone,PartialEq)] pub enum TxProcessingResult{Deployed(String),Called(ExecResult)}
#[derive(Debug,Clone,PartialEq,Eq)] pub enum ContractError{WrongTxType,NotAContractTx,InvalidPayload(String),ContractNotFound(String),ExecutionFailed(String)}
pub fn build_deploy_payload(bytecode:&[u8])->Vec<u8>{let mut p=Vec::new();p.extend_from_slice(&(bytecode.len() as u32).to_be_bytes());p.extend_from_slice(bytecode);p}
pub fn build_call_payload(addr:&str,call_data:&[u8])->Vec<u8>{let mut p=Vec::new();let ab=addr.as_bytes();p.extend_from_slice(&(ab.len() as u16).to_be_bytes());p.extend_from_slice(ab);p.extend_from_slice(call_data);p}
fn hex(bytes:&[u8])->String{let mut s=String::new();for&b in bytes{s.push_str(&format!("{:02x}",b));}s}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::vm::{Opcode, build_bytecode};
    fn setup() -> ContractExecutor { let vm = Arc::new(VmEngine::new(1_000_000)); let state = Arc::new(crate::mempool::StateDb::new()); state.deposit("did:alice", 10_000_000); ContractExecutor::new(vm, state) }
    fn mk_deploy(s: &str, bc: Vec<u8>, n: u64) -> Transaction { Transaction::new(TxType::ContractDeploy, s.into(), None, 0, 10, 100_000, n, 1000, build_deploy_payload(&bc), [0;64], [0x42;32]) }
    fn mk_call(s: &str, addr: &str, n: u64) -> Transaction { Transaction::new(TxType::ContractCall, s.into(), None, 0, 10, 100_000, n, 1000, build_call_payload(addr, &[]), [0;64], [0x42;32]) }
    #[test] fn test_deploy() { let e = setup(); let bc = build_bytecode(&[(Opcode::Push,Some(42)),(Opcode::Ret,None)]); let r = e.process_tx(&mk_deploy("did:alice", bc, 0)).unwrap(); match r { TxProcessingResult::Deployed(a) => assert!(a.starts_with("did:contract:")), _ => panic!() } }
    #[test] fn test_deploy_det_addr() { let e = setup(); let bc = vec![Opcode::Halt as u8]; let a1 = match e.process_tx(&mk_deploy("did:alice", bc.clone(), 0)).unwrap() { TxProcessingResult::Deployed(a) => a, _ => panic!() }; let a2 = match e.process_tx(&mk_deploy("did:alice", bc, 0)).unwrap() { TxProcessingResult::Deployed(a) => a, _ => panic!() }; assert_eq!(a1, a2); }
    #[test] fn test_deploy_diff_senders() { let e = setup(); let bc = vec![Opcode::Halt as u8]; let a1 = match e.process_tx(&mk_deploy("did:alice", bc.clone(), 0)).unwrap() { TxProcessingResult::Deployed(a) => a, _ => panic!() }; let a2 = match e.process_tx(&mk_deploy("did:bob", bc, 0)).unwrap() { TxProcessingResult::Deployed(a) => a, _ => panic!() }; assert_ne!(a1, a2); }
    #[test] fn test_deploy_wrong_type() { let e = setup(); let t = Transaction::new(TxType::Transfer, "a".into(), Some("b".into()), 100, 10, 50000, 0, 1000, vec![], [0;64], [0x42;32]); assert_eq!(e.process_tx(&t), Err(ContractError::NotAContractTx)); }
    #[test] fn test_deploy_bad_payload() { let e = setup(); let mut t = mk_deploy("did:alice", vec![Opcode::Halt as u8], 0); t.payload = vec![0; 2]; assert_eq!(e.process_deploy(&t), Err(ContractError::InvalidPayload("too short".into()))); }
    #[test] fn test_call() { let e = setup(); let bc = build_bytecode(&[(Opcode::Push,Some(42)),(Opcode::Ret,None)]); let addr = match e.process_tx(&mk_deploy("did:alice", bc, 0)).unwrap() { TxProcessingResult::Deployed(a) => a, _ => panic!() }; let r = e.process_tx(&mk_call("did:bob", &addr, 0)).unwrap(); match r { TxProcessingResult::Called(r) => { assert!(r.success); assert_eq!(r.return_value, 42); } _ => panic!() } }
    #[test] fn test_call_not_found() { let e = setup(); assert_eq!(e.process_call(&mk_call("did:alice", "did:contract:dead", 0)), Err(ContractError::ContractNotFound("did:contract:dead".into()))); }
    #[test] fn test_call_wrong_type() { let e = setup(); let t = Transaction::new(TxType::Transfer, "a".into(), Some("b".into()), 100, 10, 50000, 0, 1000, vec![], [0;64], [0x42;32]); assert_eq!(e.process_call(&t), Err(ContractError::WrongTxType)); }
    #[test] fn test_call_storage() { let e = setup(); let store = build_bytecode(&[(Opcode::Push,Some(999)),(Opcode::Push,Some(1)),(Opcode::Store,None),(Opcode::Halt,None)]); let addr = match e.process_tx(&mk_deploy("did:alice", store, 0)).unwrap() { TxProcessingResult::Deployed(a) => a, _ => panic!() }; let load = build_bytecode(&[(Opcode::Push,Some(1)),(Opcode::Load,None),(Opcode::Ret,None)]); e.vm().registry.contracts.lock().get_mut(&addr).unwrap().bytecode = load; let r = match e.process_tx(&mk_call("did:bob", &addr, 0)).unwrap() { TxProcessingResult::Called(r) => r, _ => panic!() }; assert_eq!(r.return_value, 999); }
    #[test] fn test_deploy_payload_builder() { let p = build_deploy_payload(&[0x01,0x02]); assert_eq!(p.len(), 6); assert_eq!(u32::from_be_bytes([p[0],p[1],p[2],p[3]]), 2); }
    #[test] fn test_call_payload_builder() { let p = build_call_payload("addr", &[0x42]); assert_eq!(u16::from_be_bytes([p[0],p[1]]), 4); assert_eq!(&p[2..6], b"addr"); }
    #[test] fn test_deploy_then_call() { let e = setup(); let bc = build_bytecode(&[(Opcode::Push,Some(7)),(Opcode::Push,Some(6)),(Opcode::Mul,None),(Opcode::Ret,None)]); let addr = match e.process_tx(&mk_deploy("did:alice", bc, 0)).unwrap() { TxProcessingResult::Deployed(a) => a, _ => panic!() }; let r = e.process_tx(&mk_call("did:bob", &addr, 0)).unwrap(); match r { TxProcessingResult::Called(r) => assert_eq!(r.return_value, 42), _ => panic!() } }
}
