// Copyright (c) 2026 Michael Wroblewski / ShivaCore / A-TownChain-Okosystems. All Rights Reserved.
// ══════════════════════════════════════════════════════════════════════════════
// K-Sprint 48 — Loadable Kernel Modules (LKM)
// Dynamic module loading/unloading with init/exit functions, dependency graph,
// symbol exports, reference counting, module parameters, safety checks.
// insmod / rmmod / modprobe equivalent.
// ══════════════════════════════════════════════════════════════════════════════

use std::collections::{BTreeMap, BTreeSet, HashMap, VecDeque};
use std::sync::atomic::{AtomicU64, Ordering};

static MODULE_SEQ: AtomicU64 = AtomicU64::new(0);

fn next_module_id() -> u64 { MODULE_SEQ.fetch_add(1, Ordering::SeqCst) }

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash)]
pub enum ModuleState { Registered, Loading, Active, Unloading, Failed, Unloaded }
impl ModuleState {
    pub fn name(&self) -> &'static str { match self { ModuleState::Registered=>"REGISTERED", ModuleState::Loading=>"LOADING", ModuleState::Active=>"ACTIVE", ModuleState::Unloading=>"UNLOADING", ModuleState::Failed=>"FAILED", ModuleState::Unloaded=>"UNLOADED" } }
    pub fn is_active(&self) -> bool { matches!(self, Self::Active) }
    pub fn is_loading(&self) -> bool { matches!(self, Self::Loading) }
    pub fn is_unloading(&self) -> bool { matches!(self, Self::Unloading) }
    pub fn is_terminal(&self) -> bool { matches!(self, Self::Unloaded) }
}
impl std::fmt::Display for ModuleState { fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { write!(f, "{}", self.name()) } }

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum ModulePriority { Core=0, Driver=1, FileSystem=2, Network=3, Security=4, Utility=5, Custom=9 }
impl ModulePriority { pub fn name(&self)->&'static str { match self { Self::Core=>"core",Self::Driver=>"driver",Self::FileSystem=>"filesystem",Self::Network=>"network",Self::Security=>"security",Self::Utility=>"utility",Self::Custom=>"custom" } } }

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ModuleLicense { Gpl, Mit, Bsd, Apache, Proprietary }
impl ModuleLicense { pub fn name(&self)->&'static str { match self { Self::Gpl=>"GPL",Self::Mit=>"MIT",Self::Bsd=>"BSD",Self::Apache=>"Apache-2.0",Self::Proprietary=>"Proprietary" } } pub fn is_open_source(&self)->bool {!matches!(self,Self::Proprietary)} pub fn taints_kernel(&self)->bool {matches!(self,Self::Proprietary)} }

#[derive(Clone, Debug)]
pub struct ModuleParam { pub name:String,pub description:String,pub default_value:String,pub current_value:String,pub read_only:bool,pub param_type:ParamType }
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ParamType { Bool, Int, Uint, String, List }
impl ParamType { pub fn name(&self)->&'static str {match self {Self::Bool=>"bool",Self::Int=>"int",Self::Uint=>"uint",Self::String=>"string",Self::List=>"list"}} pub fn validate(&self,value:&str)->bool {match self {Self::Bool=>value=="true"||value=="false"||value=="1"||value=="0",Self::Int=>value.parse::<i64>().is_ok(),Self::Uint=>value.parse::<u64>().is_ok(),Self::String=>!value.is_empty(),Self::List=>true}} }
impl ModuleParam { pub fn new(name:&str,ptype:ParamType,default:&str,desc:&str)->Self{Self{name:name.to_string(),description:desc.to_string(),default_value:default.to_string(),current_value:default.to_string(),read_only:false,param_type:ptype}} pub fn readonly(name:&str,ptype:ParamType,default:&str,desc:&str)->Self{Self{name:name.to_string(),description:desc.to_string(),default_value:default.to_string(),current_value:default.to_string(),read_only:true,param_type:ptype}} pub fn set(&mut self,value:&str)->Result<(),String>{if self.read_only{return Err(format!("Parameter '{}' is read-only",self.name))} if !self.param_type.validate(value){return Err(format!("Invalid value '{}' for type {} ({})",value,self.param_type.name(),self.name))} self.current_value=value.to_string();Ok(())} pub fn reset(&mut self){self.current_value=self.default_value.clone()} pub fn is_default(&self)->bool{self.current_value==self.default_value} }

#[derive(Clone, Debug)]
pub struct ExportedSymbol { pub name:String,pub module_id:u64,pub module_name:String,pub address:u64,pub size:usize,pub ref_count:u64,pub symbol_type:SymbolType }
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum SymbolType { Function, Variable, Constant, Struct, Trait }
impl SymbolType { pub fn name(&self)->&'static str{match self{Self::Function=>"fn",Self::Variable=>"var",Self::Constant=>"const",Self::Struct=>"struct",Self::Trait=>"trait"}} }
impl ExportedSymbol { pub fn new(name:&str,module_id:u64,module_name:&str,stype:SymbolType)->Self{Self{name:name.to_string(),module_id,module_name:module_name.to_string(),address:0xDEAD_0000+module_id*0x1000,size:0,ref_count:0,symbol_type:stype}} }

#[derive(Clone, Debug)]
pub struct ModuleStats { pub load_count:u64,pub unload_count:u64,pub init_time_us:u64,pub exit_time_us:u64,pub last_load_timestamp:u64,pub last_unload_timestamp:u64,pub error_count:u64,pub last_error:Option<String>,pub memory_used:u64,pub symbols_exported:usize,pub symbols_imported:usize }
impl Default for ModuleStats {fn default()->Self{Self{load_count:0,unload_count:0,init_time_us:0,exit_time_us:0,last_load_timestamp:0,last_unload_timestamp:0,error_count:0,last_error:None,memory_used:0,symbols_exported:0,symbols_imported:0}}}

#[derive(Clone, Debug)]
pub struct ModuleDescriptor { pub id:u64,pub name:String,pub version:String,pub description:String,pub author:String,pub license:ModuleLicense,pub priority:ModulePriority,pub state:ModuleState,pub dependencies:Vec<String>,pub optional_deps:Vec<String>,pub conflicts:Vec<String>,pub provides:Vec<String>,pub params:Vec<ModuleParam>,pub exports:Vec<ExportedSymbol>,pub imports:Vec<String>,pub stats:ModuleStats,pub ref_count:u64,pub load_order:u64,pub auto_load:bool,pub kernel_version:String }
impl ModuleDescriptor {
 pub fn new(name:&str,version:&str)->Self{Self{id:next_module_id(),name:name.to_string(),version:version.to_string(),description:String::new(),author:String::new(),license:ModuleLicense::Gpl,priority:ModulePriority::Utility,state:ModuleState::Registered,dependencies:Vec::new(),optional_deps:Vec::new(),conflicts:Vec::new(),provides:Vec::new(),params:Vec::new(),exports:Vec::new(),imports:Vec::new(),stats:ModuleStats::default(),ref_count:0,load_order:0,auto_load:false,kernel_version:String::new()}}
 pub fn with_description(mut self,desc:&str)->Self{self.description=desc.to_string();self} pub fn with_author(mut self,author:&str)->Self{self.author=author.to_string();self} pub fn with_license(mut self,license:ModuleLicense)->Self{self.license=license;self} pub fn with_priority(mut self,priority:ModulePriority)->Self{self.priority=priority;self} pub fn with_dependencies(mut self,deps:&[&str])->Self{self.dependencies=deps.iter().map(|s|s.to_string()).collect();self} pub fn with_optional_deps(mut self,deps:&[&str])->Self{self.optional_deps=deps.iter().map(|s|s.to_string()).collect();self} pub fn with_conflicts(mut self,conflicts:&[&str])->Self{self.conflicts=conflicts.iter().map(|s|s.to_string()).collect();self} pub fn with_provides(mut self,provides:&[&str])->Self{self.provides=provides.iter().map(|s|s.to_string()).collect();self} pub fn with_param(mut self,param:ModuleParam)->Self{self.params.push(param);self}
 pub fn with_export(mut self,symbol:ExportedSymbol)->Self{self.exports.push(symbol);self}
 pub fn with_auto_load(mut self,auto:bool)->Self{self.auto_load=auto;self} pub fn add_ref(&mut self)->u64{self.ref_count+=1;self.ref_count} pub fn release_ref(&mut self)->Result<u64,String>{if self.ref_count==0{return Err(format!("Module {} has no references to release",self.name))} self.ref_count-=1;Ok(self.ref_count)} pub fn can_unload(&self)->bool{self.state==ModuleState::Active&&self.ref_count==0} pub fn get_param(&self,name:&str)->Option<&ModuleParam>{self.params.iter().find(|p|p.name==name)} pub fn get_param_mut(&mut self,name:&str)->Option<&mut ModuleParam>{self.params.iter_mut().find(|p|p.name==name)} pub fn set_param(&mut self,name:&str,value:&str)->Result<(),String>{let p=self.get_param_mut(name).ok_or_else(||format!("Parameter '{}' not found in module '{}'",name,self.name))?;p.set(value)} pub fn reset_params(&mut self){for p in &mut self.params{p.reset()}}
}

#[derive(Clone, Debug)]
pub struct ModuleEvent { pub event_id:u64,pub timestamp:u64,pub event_type:ModuleEventType,pub module_name:String,pub module_id:u64,pub message:String }
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ModuleEventType { Registered,LoadStarted,LoadSucceeded,LoadFailed,UnloadStarted,UnloadSucceeded,UnloadFailed,ParamChanged,SymbolResolved,SymbolUnresolved,RefAcquired,RefReleased,AutoLoaded,ConflictDetected,DependencyMissing,CircularDependency }
impl ModuleEventType {pub fn name(&self)->&'static str{match self{Self::Registered=>"REGISTERED",Self::LoadStarted=>"LOAD_STARTED",Self::LoadSucceeded=>"LOAD_SUCCEEDED",Self::LoadFailed=>"LOAD_FAILED",Self::UnloadStarted=>"UNLOAD_STARTED",Self::UnloadSucceeded=>"UNLOAD_SUCCEEDED",Self::UnloadFailed=>"UNLOAD_FAILED",Self::ParamChanged=>"PARAM_CHANGED",Self::SymbolResolved=>"SYMBOL_RESOLVED",Self::SymbolUnresolved=>"SYMBOL_UNRESOLVED",Self::RefAcquired=>"REF_ACQUIRED",Self::RefReleased=>"REF_RELEASED",Self::AutoLoaded=>"AUTO_LOADED",Self::ConflictDetected=>"CONFLICT_DETECTED",Self::DependencyMissing=>"DEPENDENCY_MISSING",Self::CircularDependency=>"CIRCULAR_DEPENDENCY"}}}

#[derive(Clone, Debug)]
pub struct DependencyGraph { nodes:BTreeSet<String>,edges:HashMap<String,BTreeSet<String>>,reverse_edges:HashMap<String,BTreeSet<String>> }
impl Default for DependencyGraph {fn default()->Self{Self{nodes:BTreeSet::new(),edges:HashMap::new(),reverse_edges:HashMap::new()}}}
impl DependencyGraph {
 pub fn new()->Self{Self::default()} pub fn add_node(&mut self,name:&str){self.nodes.insert(name.to_string());self.edges.entry(name.to_string()).or_default();self.reverse_edges.entry(name.to_string()).or_default()}
 pub fn add_edge(&mut self,from:&str,to:&str){self.nodes.insert(from.to_string());self.nodes.insert(to.to_string());self.edges.entry(from.to_string()).or_default().insert(to.to_string());self.edges.entry(to.to_string()).or_default();self.reverse_edges.entry(to.to_string()).or_default().insert(from.to_string());self.reverse_edges.entry(from.to_string()).or_default()}
 pub fn remove_node(&mut self,name:&str){self.nodes.remove(name);self.edges.remove(name);self.reverse_edges.remove(name);for deps in self.edges.values_mut(){deps.remove(name)}for dependents in self.reverse_edges.values_mut(){dependents.remove(name)}}
 pub fn has_node(&self,name:&str)->bool{self.nodes.contains(name)}
 pub fn dependencies(&self,name:&str)->Vec<String>{self.get_dependencies(name)}
 pub fn get_dependencies(&self,name:&str)->Vec<String>{self.edges.get(name).map(|s|s.iter().cloned().collect()).unwrap_or_default()}
 pub fn get_dependents(&self,name:&str)->Vec<String>{self.reverse_edges.get(name).map(|s|s.iter().cloned().collect()).unwrap_or_default()}
 pub fn has_circular(&self)->Option<Vec<String>>{let mut visited=BTreeSet::new();let mut rec_stack=BTreeSet::new();let mut path=Vec::new();for node in &self.nodes{if !visited.contains(node){if let Some(cycle)=self.dfs_cycle(node,&mut visited,&mut rec_stack,&mut path){return Some(cycle)}}}None}
 fn dfs_cycle(&self,node:&str,visited:&mut BTreeSet<String>,rec_stack:&mut BTreeSet<String>,path:&mut Vec<String>)->Option<Vec<String>>{visited.insert(node.to_string());rec_stack.insert(node.to_string());path.push(node.to_string());if let Some(deps)=self.edges.get(node){for dep in deps{if !visited.contains(dep){if let Some(cycle)=self.dfs_cycle(dep,visited,rec_stack,path){return Some(cycle)}}else if rec_stack.contains(dep){let cycle_start=path.iter().position(|n|n==dep).unwrap();return Some(path[cycle_start..].to_vec())}}}path.pop();rec_stack.remove(node);None}
 pub fn topological_sort(&self)->Result<Vec<String>,Vec<String>>{let mut indegree:HashMap<String,usize>=self.nodes.iter().cloned().map(|n|(n,0)).collect();for (module,deps) in &self.edges{if !self.nodes.contains(module){continue}for dep in deps{if self.nodes.contains(dep){*indegree.get_mut(module).expect("node initialized")+=1}}}let mut ready:BTreeSet<String>=indegree.iter().filter_map(|(n,d)|(*d==0).then_some(n.clone())).collect();let mut result=Vec::with_capacity(self.nodes.len());while let Some(node)=ready.pop_first(){result.push(node.clone());if let Some(dependents)=self.reverse_edges.get(&node){for dependent in dependents{let d=indegree.get_mut(dependent).expect("dependent initialized");*d-=1;if *d==0{ready.insert(dependent.clone())}}}}if result.len()==self.nodes.len(){Ok(result)}else{Err(self.nodes.iter().filter(|n|!result.contains(n)).cloned().collect())}}
 pub fn load_order(&self,target:&str)->Result<Vec<String>,String>{let mut order=Vec::new();let mut visited=BTreeSet::new();self.dfs_load_order(target,&mut visited,&mut order)?;if let Some(pos)=order.iter().position(|n|n==target){order.remove(pos)}order.push(target.to_string());Ok(order)}
 fn dfs_load_order(&self,node:&str,visited:&mut BTreeSet<String>,order:&mut Vec<String>)->Result<(),String>{if visited.contains(node){return Ok(())}visited.insert(node.to_string());if let Some(deps)=self.edges.get(node){for dep in deps{if !self.nodes.contains(dep){return Err(format!("Dependency '{}' not found (required by '{}')",dep,node))}self.dfs_load_order(dep,visited,order)?}}order.push(node.to_string());Ok(())}
 pub fn node_count(&self)->usize{self.nodes.len()} pub fn edge_count(&self)->usize{self.edges.values().map(|s|s.len()).sum()}
}

#[derive(Clone, Debug)]
pub struct SymbolTable { symbols:BTreeMap<String,ExportedSymbol>,imports:HashMap<String,BTreeSet<u64>> }
impl Default for SymbolTable {fn default()->Self{Self{symbols:BTreeMap::new(),imports:HashMap::new()}}}
impl SymbolTable {pub fn new()->Self{Self::default()} pub fn register(&mut self,symbol:ExportedSymbol)->Result<(),String>{if self.symbols.contains_key(&symbol.name){return Err(format!("Symbol '{}' already registered",symbol.name))}self.symbols.insert(symbol.name.clone(),symbol);Ok(())} pub fn unregister_module(&mut self,module_id:u64)->Vec<String>{let names:Vec<String>=self.symbols.iter().filter(|(_,s)|s.module_id==module_id).map(|(n,_)|n.clone()).collect();for n in &names{self.symbols.remove(n);self.imports.remove(n)}names} pub fn resolve(&mut self,name:&str)->Result<(),String>{if !self.symbols.contains_key(name){return Err(format!("Symbol '{}' not found",name))}self.symbols.get_mut(name).unwrap().ref_count+=1;self.imports.entry(name.to_string()).or_default();Ok(())} pub fn release(&mut self,name:&str)->Result<(),String>{let s=self.symbols.get_mut(name).ok_or_else(||format!("Symbol '{}' not found",name))?;if s.ref_count==0{return Err(format!("Symbol '{}' has no references",name))}s.ref_count-=1;Ok(())} pub fn unresolved_imports(&self,imports:&[String])->Vec<String>{imports.iter().filter(|n|!self.symbols.contains_key(*n)).cloned().collect()} pub fn contains(&self,name:&str)->bool{self.symbols.contains_key(name)} pub fn lookup(&self,name:&str)->Option<&ExportedSymbol>{self.symbols.get(name)} pub fn all_symbols(&self)->Vec<&ExportedSymbol>{self.symbols.values().collect()} pub fn symbol_count(&self)->usize{self.symbols.len()} }

#[derive(Clone,Debug)]
pub struct ModuleRegistry {modules:BTreeMap<String,ModuleDescriptor>,by_id:HashMap<u64,String>,dep_graph:DependencyGraph,symbol_table:SymbolTable,events:VecDeque<ModuleEvent>,next_event_id:u64,load_counter:u64,kernel_tainted:bool,max_events:usize}
impl Default for ModuleRegistry {fn default()->Self{Self{modules:BTreeMap::new(),by_id:HashMap::new(),dep_graph:DependencyGraph::new(),symbol_table:SymbolTable::new(),events:VecDeque::new(),next_event_id:0,load_counter:0,kernel_tainted:false,max_events:1000}}}
impl ModuleRegistry {
 pub fn new()->Self{Self::default()}
 fn log_event(&mut self,event_type:ModuleEventType,module_name:&str,module_id:u64,message:&str){let event=ModuleEvent{event_id:self.next_event_id,timestamp:0,event_type,module_name:module_name.to_string(),module_id,message:message.to_string()};self.next_event_id+=1;self.events.push_back(event);if self.events.len()>self.max_events{self.events.pop_front()}}
 pub fn register(&mut self,mut module:ModuleDescriptor)->Result<u64,String>{if self.modules.contains_key(&module.name){return Err(format!("Module '{}' already registered",module.name))}for conflict in &module.conflicts{if let Some(conflict_mod)=self.modules.get(conflict){if conflict_mod.state.is_active(){self.log_event(ModuleEventType::ConflictDetected,&module.name,module.id,&format!("Conflicts with active module '{}'",conflict));return Err(format!("Module '{}' conflicts with active module '{}'",module.name,conflict))}}}self.dep_graph.add_node(&module.name);for dep in &module.dependencies{self.dep_graph.add_edge(&module.name,dep)}for dep in &module.optional_deps{self.dep_graph.add_edge(&module.name,dep)}if let Some(cycle)=self.dep_graph.has_circular(){self.dep_graph.remove_node(&module.name);self.log_event(ModuleEventType::CircularDependency,&module.name,module.id,&format!("Circular dependency detected: {}",cycle.join(" -> ")));return Err(format!("Circular dependency detected: {}",cycle.join(" -> ")))}let id=module.id;let name=module.name.clone();self.by_id.insert(id,name.clone());self.modules.insert(name,module);Ok(id)}
 pub fn load(&mut self,name:&str)->Result<u64,String>{let module=self.modules.get(name).ok_or_else(||format!("Module '{}' not found",name))?;if module.state.is_active(){return Err(format!("Module '{}' is already active",name))}if module.state.is_loading(){return Err(format!("Module '{}' is already loading",name))}let module_name=name.to_string();let module_id=module.id;let load_order=self.dep_graph.load_order(&module_name).map_err(|e|{self.log_event(ModuleEventType::DependencyMissing,&module_name,module_id,&e);e})?;for dep_name in &load_order{if dep_name==&module_name{continue}if let Some(dep)=self.modules.get(dep_name){if !dep.state.is_active(){self.load(dep_name)?}}else{return Err(format!("Required dependency '{}' not found",dep_name))}}let module=self.modules.get_mut(name).unwrap();module.state=ModuleState::Loading;let imports=module.imports.clone();let unresolved=self.symbol_table.unresolved_imports(&imports);let optional_set:BTreeSet<String>=module.optional_deps.iter().cloned().collect();let truly_unresolved:Vec<String>=unresolved.into_iter().filter(|s|!optional_set.contains(s)).collect();if !truly_unresolved.is_empty(){let module=self.modules.get_mut(name).unwrap();module.state=ModuleState::Failed;module.stats.error_count+=1;module.stats.last_error=Some(format!("Unresolved symbols: {}",truly_unresolved.join(", ")));return Err(format!("Module '{}' has unresolved symbols: {}",name,truly_unresolved.join(", ")))}let exports=module.exports.clone();let mid=module.id;for export in exports{self.symbol_table.register(export).map_err(|e|{let module=self.modules.get_mut(name).unwrap();module.state=ModuleState::Failed;module.stats.error_count+=1;module.stats.last_error=Some(e.clone());e})?}for import in &imports{self.symbol_table.resolve(import).map_err(|e|{let module=self.modules.get_mut(name).unwrap();module.state=ModuleState::Failed;module.stats.error_count+=1;module.stats.last_error=Some(e.clone());e})?}if module.license.taints_kernel(){self.kernel_tainted=true}let module=self.modules.get_mut(name).unwrap();module.state=ModuleState::Active;module.stats.load_count+=1;module.load_order=self.load_counter;self.load_counter+=1;module.stats.symbols_exported=module.exports.len();module.stats.symbols_imported=module.imports.len();self.log_event(ModuleEventType::LoadSucceeded,name,module.id,"Module loaded successfully");Ok(module.id)}
 pub fn unload(&mut self,name:&str)->Result<(),String>{let module=self.modules.get(name).ok_or_else(||format!("Module '{}' not found",name))?;if !module.state.is_active(){return Err(format!("Module '{}' is not active (state: {})",name,module.state))}let module_id=module.id;let dependents=self.dep_graph.get_dependents(name);let active_dependents:Vec<String>=dependents.iter().filter(|dep|self.modules.get(*dep).map(|m|m.state.is_active()).unwrap_or(false)).cloned().collect();if !active_dependents.is_empty(){return Err(format!("Cannot unload '{}': active dependents: {}",name,active_dependents.join(", ")))}if module.ref_count>0{return Err(format!("Cannot unload '{}': {} references still held",name,module.ref_count))}let module=self.modules.get_mut(name).unwrap();module.state=ModuleState::Unloading;let removed_symbols=self.symbol_table.unregister_module(module_id);let imports=module.imports.clone();for import in &imports{if self.symbol_table.contains(import){let _=self.symbol_table.release(import)}}let module=self.modules.get_mut(name).unwrap();module.state=ModuleState::Unloaded;module.stats.unload_count+=1;module.stats.symbols_exported=0;module.stats.symbols_imported=0;for p in &mut module.params{p.reset()}let _=removed_symbols;Ok(())}
 pub fn reload(&mut self,name:&str)->Result<(),String>{self.unload(name)?;self.modules.get_mut(name).unwrap().state=ModuleState::Registered;self.load(name)?;Ok(())}
 pub fn auto_load_all(&mut self)->Vec<Result<u64,String>>{let mut names:Vec<(String,ModulePriority)>=self.modules.iter().filter(|(_,m)|m.auto_load&&!m.state.is_active()).map(|(n,m)|(n.clone(),m.priority)).collect();names.sort_by_key(|(_,p)|*p);names.into_iter().map(|(n,_)|self.load(&n)).collect()}
 pub fn acquire_ref(&mut self,name:&str)->Result<u64,String>{let m=self.modules.get_mut(name).ok_or_else(||format!("Module '{}' not found",name))?;if !m.state.is_active(){return Err(format!("Module '{}' is not active",name))}Ok(m.add_ref())}
 pub fn release_ref(&mut self,name:&str)->Result<u64,String>{let m=self.modules.get_mut(name).ok_or_else(||format!("Module '{}' not found",name))?;m.release_ref()}
 pub fn lookup_symbol(&self,name:&str)->Option<&ExportedSymbol>{self.symbol_table.lookup(name)} pub fn resolve_symbol(&mut self,name:&str)->Result<(),String>{self.symbol_table.resolve(name)} pub fn symbol_count(&self)->usize{self.symbol_table.symbol_count()} pub fn get(&self,name:&str)->Option<&ModuleDescriptor>{self.modules.get(name)} pub fn get_mut(&mut self,name:&str)->Option<&mut ModuleDescriptor>{self.modules.get_mut(name)} pub fn get_by_id(&self,id:u64)->Option<&ModuleDescriptor>{self.by_id.get(&id).and_then(|n|self.modules.get(n))} pub fn contains(&self,name:&str)->bool{self.modules.contains_key(name)} pub fn module_count(&self)->usize{self.modules.len()} pub fn active_count(&self)->usize{self.modules.values().filter(|m|m.state.is_active()).count()} pub fn loaded_count(&self)->usize{self.modules.values().filter(|m|m.state.is_active()||m.state==ModuleState::Unloaded).count()} pub fn is_tainted(&self)->bool{self.kernel_tainted} pub fn list_modules(&self)->Vec<&ModuleDescriptor>{let mut v:Vec<_>=self.modules.values().collect();v.sort_by(|a,b|a.name.cmp(&b.name));v} pub fn list_active(&self)->Vec<&ModuleDescriptor>{let mut v:Vec<_>=self.modules.values().filter(|m|m.state.is_active()).collect();v.sort_by(|a,b|a.load_order.cmp(&b.load_order));v} pub fn list_by_priority(&self,p:ModulePriority)->Vec<&ModuleDescriptor>{self.modules.values().filter(|m|m.priority==p).collect()} pub fn list_by_state(&self,s:ModuleState)->Vec<&ModuleDescriptor>{self.modules.values().filter(|m|m.state==s).collect()}
 pub fn set_param(&mut self,module:&str,param:&str,value:&str)->Result<(),String>{let m=self.modules.get_mut(module).ok_or_else(||format!("Module '{}' not found",module))?;if !m.state.is_active(){return Err(format!("Module '{}' is not active",module))}m.set_param(param,value)} pub fn get_param(&self,module:&str,param:&str)->Result<&str,String>{let m=self.modules.get(module).ok_or_else(||format!("Module '{}' not found",module))?;let p=m.get_param(param).ok_or_else(||format!("Parameter '{}' not found",param))?;Ok(&p.current_value)} pub fn dependency_graph(&self)->&DependencyGraph{&self.dep_graph} pub fn symbol_table(&self)->&SymbolTable{&self.symbol_table}
}

pub struct ModuleBuilder { module:ModuleDescriptor }
impl ModuleBuilder {pub fn new(name:&str,version:&str)->Self{Self{module:ModuleDescriptor::new(name,version)}} pub fn description(mut self,d:&str)->Self{self.module.description=d.to_string();self} pub fn author(mut self,a:&str)->Self{self.module.author=a.to_string();self} pub fn license(mut self,l:ModuleLicense)->Self{self.module.license=l;self} pub fn priority(mut self,p:ModulePriority)->Self{self.module.priority=p;self} pub fn depends_on(mut self,d:&[&str])->Self{self.module.dependencies=d.iter().map(|s|s.to_string()).collect();self} pub fn optional_depends_on(mut self,d:&[&str])->Self{self.module.optional_deps=d.iter().map(|s|s.to_string()).collect();self} pub fn conflicts_with(mut self,d:&[&str])->Self{self.module.conflicts=d.iter().map(|s|s.to_string()).collect();self} pub fn provides(mut self,d:&[&str])->Self{self.module.provides=d.iter().map(|s|s.to_string()).collect();self} pub fn param(mut self,n:&str,t:ParamType,d:&str,x:&str)->Self{self.module.params.push(ModuleParam::new(n,t,d,x));self} pub fn readonly_param(mut self,n:&str,t:ParamType,d:&str,x:&str)->Self{self.module.params.push(ModuleParam::readonly(n,t,d,x));self} pub fn export(mut self,n:&str,t:SymbolType)->Self{let s=ExportedSymbol::new(n,self.module.id,&self.module.name,t);self.module.exports.push(s);self} pub fn import_symbol(mut self,n:&str)->Self{self.module.imports.push(n.to_string());self} pub fn auto_load(mut self)->Self{self.module.auto_load=true;self} pub fn build(self)->ModuleDescriptor{self.module}}

pub fn create_builtin_modules()->Vec<ModuleDescriptor>{let mut modules=Vec::new();modules.push(ModuleBuilder::new("kalloc","1.0.0").description("Kernel slab/page allocator").author("ShivaCore").license(ModuleLicense::Gpl).priority(ModulePriority::Core).provides(&["kmalloc","kfree"]).export("kmalloc",SymbolType::Function).export("kfree",SymbolType::Function).param("slab_size",ParamType::Uint,"4096","Default slab size in bytes").param("debug",ParamType::Bool,"false","Enable debug allocations").auto_load().build());modules.push(ModuleBuilder::new("ksched","1.0.0").description("Kernel scheduler").author("ShivaCore").license(ModuleLicense::Gpl).priority(ModulePriority::Core).depends_on(&["kalloc"]).export("schedule",SymbolType::Function).export("yield_cpu",SymbolType::Function).auto_load().build());modules}

#[cfg(test)]
mod tests {
    use super::*;
    #[test] fn dependency_api_is_owned_and_deterministic(){let mut g=DependencyGraph::new();g.add_edge("app","core");g.add_edge("app","bus");assert_eq!(g.dependencies("app"),vec!["bus","core"]);}
    #[test] fn topological_sort_is_dependency_first(){let mut g=DependencyGraph::new();g.add_edge("app","core");g.add_edge("app","bus");assert_eq!(g.topological_sort().unwrap(),vec!["bus","core","app"]);}
    #[test] fn unresolved_required_import_fails_closed_without_optional_deps(){let mut r=ModuleRegistry::new();let m=ModuleBuilder::new("consumer","1").import_symbol("missing").build();r.register(m).unwrap();assert!(r.load("consumer").is_err());}
    #[test] fn export_does_not_create_import(){let m=ModuleBuilder::new("provider","1").export("service",SymbolType::Function).build();assert!(m.imports.is_empty());assert_eq!(m.exports.len(),1);}
    #[test] fn diamond_dependencies_are_deterministic(){let mut g=DependencyGraph::new();g.add_edge("app","left");g.add_edge("app","right");g.add_edge("left","core");g.add_edge("right","core");assert_eq!(g.load_order("app").unwrap(),vec!["core","left","right","app"]);}
}
