// Copyright (c) 2026 Michael Wroblewski / ShivaCore / A-TownChain-Okosystems. All Rights Reserved.
// K-Sprint 19 — Contract VM (ShivaVM)
use alloc::vec;
use alloc::collections::BTreeMap; use alloc::vec::Vec; use alloc::string::{String,ToString}; use alloc::sync::Arc; use spin::Mutex;
#[derive(Clone,Copy,Debug,PartialEq,Eq)] #[repr(u8)]
pub enum Opcode{Nop=0x00,Push=0x01,Pop=0x02,Add=0x10,Sub=0x11,Mul=0x12,Div=0x13,Mod=0x14,Eq=0x20,Ne=0x21,Lt=0x22,Gt=0x23,Lte=0x24,Gte=0x25,And=0x30,Or=0x31,Not=0x32,Jump=0x40,JumpIf=0x41,JumpIfNot=0x42,Call=0x50,Ret=0x51,Load=0x60,Store=0x61,Log=0x70,Self_=0x80,Caller=0x81,Balance=0x82,Transfer=0x83,Halt=0xFF}
impl Opcode{pub fn from_u8(v:u8)->Option<Self>{match v{0x00=>Some(Opcode::Nop),0x01=>Some(Opcode::Push),0x02=>Some(Opcode::Pop),0x10=>Some(Opcode::Add),0x11=>Some(Opcode::Sub),0x12=>Some(Opcode::Mul),0x13=>Some(Opcode::Div),0x14=>Some(Opcode::Mod),0x20=>Some(Opcode::Eq),0x21=>Some(Opcode::Ne),0x22=>Some(Opcode::Lt),0x23=>Some(Opcode::Gt),0x24=>Some(Opcode::Lte),0x25=>Some(Opcode::Gte),0x30=>Some(Opcode::And),0x31=>Some(Opcode::Or),0x32=>Some(Opcode::Not),0x40=>Some(Opcode::Jump),0x41=>Some(Opcode::JumpIf),0x42=>Some(Opcode::JumpIfNot),0x50=>Some(Opcode::Call),0x51=>Some(Opcode::Ret),0x60=>Some(Opcode::Load),0x61=>Some(Opcode::Store),0x70=>Some(Opcode::Log),0x80=>Some(Opcode::Self_),0x81=>Some(Opcode::Caller),0x82=>Some(Opcode::Balance),0x83=>Some(Opcode::Transfer),0xFF=>Some(Opcode::Halt),_=>None}}pub fn gas_cost(&self)->u64{match self{Opcode::Nop=>1,Opcode::Push=>3,Opcode::Pop=>2,Opcode::Add|Opcode::Sub|Opcode::Mul|Opcode::Mod=>5,Opcode::Div=>10,Opcode::Eq|Opcode::Ne|Opcode::Lt|Opcode::Gt|Opcode::Lte|Opcode::Gte=>3,Opcode::And|Opcode::Or|Opcode::Not=>3,Opcode::Jump|Opcode::JumpIf|Opcode::JumpIfNot=>8,Opcode::Call=>50,Opcode::Ret=>5,Opcode::Load=>200,Opcode::Store=>5000,Opcode::Log=>100,Opcode::Self_|Opcode::Caller=>2,Opcode::Balance=>100,Opcode::Transfer=>1000,Opcode::Halt=>0}}}
#[derive(Debug,Clone,PartialEq,Eq)] pub enum VmError{OutOfGas,StackOverflow,StackUnderflow,InvalidOpcode(u8),InvalidJump(u64),DivisionByZero,StorageError(String),HaltReached}
#[derive(Clone,Debug,PartialEq)] pub struct ExecResult{pub success:bool,pub return_value:u64,pub gas_used:u64,pub gas_refund:u64,pub logs:Vec<LogEntry>,pub storage_changes:Vec<(u64,u64)>,pub error:Option<VmError>}
#[derive(Clone,Debug,PartialEq)] pub struct LogEntry{pub contract:String,pub topic:u64,pub data:Vec<u64>}
#[derive(Clone,Debug,PartialEq)] pub struct Contract{pub address:String,pub bytecode:Vec<u8>,pub owner_did:String,pub balance:u64,pub nonce:u64}
pub struct ContractStorage{data:Mutex<BTreeMap<(String,u64),u64>>}
impl ContractStorage{pub fn new()->Self{ContractStorage{data:Mutex::new(BTreeMap::new())}}pub fn load(&self,c:&str,k:u64)->u64{self.data.lock().get(&(c.to_string(),k)).copied().unwrap_or(0)}pub fn store(&self,c:&str,k:u64,v:u64){self.data.lock().insert((c.to_string(),k),v);}pub fn total_entries(&self)->usize{self.data.lock().len()}}
pub struct ContractRegistry{pub contracts:Mutex<BTreeMap<String,Contract>>}
impl ContractRegistry{pub fn new()->Self{ContractRegistry{contracts:Mutex::new(BTreeMap::new())}}pub fn deploy(&self,address:String,bytecode:Vec<u8>,owner_did:String){let addr_clone=address.clone();self.contracts.lock().insert(addr_clone,Contract{address,bytecode,owner_did,balance:0,nonce:0});}pub fn get(&self,address:&str)->Option<Contract>{self.contracts.lock().get(address).cloned()}pub fn exists(&self,address:&str)->bool{self.contracts.lock().contains_key(address)}pub fn count(&self)->usize{self.contracts.lock().len()}pub fn balance(&self,address:&str)->u64{self.contracts.lock().get(address).map(|c|c.balance).unwrap_or(0)}pub fn deposit(&self,address:&str,amount:u64){if let Some(c)=self.contracts.lock().get_mut(address){c.balance+=amount;}}}
pub struct ShivaVM{stack:Vec<u64>,pc:usize,gas_remaining:u64,gas_used:u64,contract_addr:String,caller_did:String,bytecode:Vec<u8>,logs:Vec<LogEntry>,storage_changes:Vec<(u64,u64)>,return_value:u64,halted:bool}
impl ShivaVM{pub fn new(contract:&Contract,caller_did:String,gas_limit:u64)->Self{ShivaVM{stack:Vec::new(),pc:0,gas_remaining:gas_limit,gas_used:0,contract_addr:contract.address.clone(),caller_did,bytecode:contract.bytecode.clone(),logs:Vec::new(),storage_changes:Vec::new(),return_value:0,halted:false}}
fn push(&mut self,v:u64)->Result<(),VmError>{if self.stack.len()>=1024{return Err(VmError::StackOverflow);}self.stack.push(v);Ok(())}fn pop(&mut self)->Result<u64,VmError>{self.stack.pop().ok_or(VmError::StackUnderflow)}
fn consume_gas(&mut self,c:u64)->Result<(),VmError>{if self.gas_remaining<c{self.gas_used+=self.gas_remaining;self.gas_remaining=0;return Err(VmError::OutOfGas);}self.gas_remaining-=c;self.gas_used+=c;Ok(())}
fn read_u64(&mut self)->Result<u64,VmError>{if self.pc+8>self.bytecode.len(){return Err(VmError::InvalidOpcode(0));}let b:[u8;8]=self.bytecode[self.pc..self.pc+8].try_into().unwrap();self.pc+=8;Ok(u64::from_be_bytes(b))}
pub fn execute(&mut self,storage:&ContractStorage,registry:&ContractRegistry)->ExecResult{loop{if self.halted{return self.ok();}if self.pc>=self.bytecode.len(){return self.ok();}let ob=self.bytecode[self.pc];self.pc+=1;let op=match Opcode::from_u8(ob){Some(o)=>o,None=>return self.err(VmError::InvalidOpcode(ob))};if let Err(e)=self.consume_gas(op.gas_cost()){return self.err(e);}match self.exec_op(op,storage,registry){Ok(())=>{}Err(VmError::HaltReached)=>{self.halted=true;return self.ok();}Err(e)=>return self.err(e),}}}
fn exec_op(&mut self,op:Opcode,storage:&ContractStorage,registry:&ContractRegistry)->Result<(),VmError>{match op{Opcode::Nop=>{}Opcode::Push=>{let v=self.read_u64()?;self.push(v)?;}Opcode::Pop=>{self.pop()?;}Opcode::Add=>{let b=self.pop()?;let a=self.pop()?;self.push(a.wrapping_add(b))?;}Opcode::Sub=>{let b=self.pop()?;let a=self.pop()?;self.push(a.wrapping_sub(b))?;}Opcode::Mul=>{let b=self.pop()?;let a=self.pop()?;self.push(a.wrapping_mul(b))?;}Opcode::Div=>{let b=self.pop()?;let a=self.pop()?;if b==0{return Err(VmError::DivisionByZero);}self.push(a/b)?;}Opcode::Mod=>{let b=self.pop()?;let a=self.pop()?;if b==0{return Err(VmError::DivisionByZero);}self.push(a%b)?;}Opcode::Eq=>{let b=self.pop()?;let a=self.pop()?;self.push(if a==b{1}else{0})?;}Opcode::Ne=>{let b=self.pop()?;let a=self.pop()?;self.push(if a!=b{1}else{0})?;}Opcode::Lt=>{let b=self.pop()?;let a=self.pop()?;self.push(if a<b{1}else{0})?;}Opcode::Gt=>{let b=self.pop()?;let a=self.pop()?;self.push(if a>b{1}else{0})?;}Opcode::Lte=>{let b=self.pop()?;let a=self.pop()?;self.push(if a<=b{1}else{0})?;}Opcode::Gte=>{let b=self.pop()?;let a=self.pop()?;self.push(if a>=b{1}else{0})?;}Opcode::And=>{let b=self.pop()?;let a=self.pop()?;self.push(if a!=0&&b!=0{1}else{0})?;}Opcode::Or=>{let b=self.pop()?;let a=self.pop()?;self.push(if a!=0||b!=0{1}else{0})?;}Opcode::Not=>{let a=self.pop()?;self.push(if a==0{1}else{0})?;}Opcode::Jump=>{let t=self.pop()?;if t as usize>=self.bytecode.len(){return Err(VmError::InvalidJump(t));}self.pc=t as usize;}Opcode::JumpIf=>{let t=self.pop()?;let c=self.pop()?;if c!=0{if t as usize>=self.bytecode.len(){return Err(VmError::InvalidJump(t));}self.pc=t as usize;}}Opcode::JumpIfNot=>{let t=self.pop()?;let c=self.pop()?;if c==0{if t as usize>=self.bytecode.len(){return Err(VmError::InvalidJump(t));}self.pc=t as usize;}}Opcode::Call=>{let f=self.pop()?;let _=self.pop()?;match f{1=>self.push(42)?,_=>self.push(0)?,}}Opcode::Ret=>{self.return_value=self.pop()?;return Err(VmError::HaltReached);}Opcode::Load=>{let k=self.pop()?;self.push(storage.load(&self.contract_addr,k))?;}Opcode::Store=>{let k=self.pop()?;let v=self.pop()?;storage.store(&self.contract_addr,k,v);self.storage_changes.push((k,v));}Opcode::Log=>{let t=self.pop()?;let d=self.pop()?;self.logs.push(LogEntry{contract:self.contract_addr.clone(),topic:t,data:vec![d]});}Opcode::Self_=>{let h=crate::security::simple_hash(self.contract_addr.as_bytes());self.push(u64::from_be_bytes(h[..8].try_into().unwrap()))?;}Opcode::Caller=>{let h=crate::security::simple_hash(self.caller_did.as_bytes());self.push(u64::from_be_bytes(h[..8].try_into().unwrap()))?;}Opcode::Balance=>{let _=self.pop()?;self.push(registry.balance(&self.contract_addr))?;}Opcode::Transfer=>{let a=self.pop()?;let _=self.pop()?;self.logs.push(LogEntry{contract:self.contract_addr.clone(),topic:0xDEAD,data:vec![a]});}Opcode::Halt=>{return Err(VmError::HaltReached);}}Ok(())}
fn ok(&self)->ExecResult{ExecResult{success:true,return_value:self.return_value,gas_used:self.gas_used,gas_refund:self.gas_remaining,logs:self.logs.clone(),storage_changes:self.storage_changes.clone(),error:None}}
fn err(&self,e:VmError)->ExecResult{ExecResult{success:false,return_value:0,gas_used:self.gas_used,gas_refund:0,logs:self.logs.clone(),storage_changes:Vec::new(),error:Some(e)}}}
pub struct VmEngine{pub storage:Arc<ContractStorage>,pub registry:Arc<ContractRegistry>,default_gas:u64}
impl VmEngine{pub fn new(default_gas:u64)->Self{VmEngine{storage:Arc::new(ContractStorage::new()),registry:Arc::new(ContractRegistry::new()),default_gas}}pub fn deploy(&self,address:String,bytecode:Vec<u8>,owner_did:String){self.registry.deploy(address,bytecode,owner_did);}pub fn call(&self,address:&str,caller_did:String,gas_limit:Option<u64>)->ExecResult{let contract=match self.registry.get(address){Some(c)=>c,None=>return ExecResult{success:false,return_value:0,gas_used:0,gas_refund:0,logs:vec![],storage_changes:vec![],error:Some(VmError::StorageError("Contract not found".into()))}};let gas=gas_limit.unwrap_or(self.default_gas);let mut vm=ShivaVM::new(&contract,caller_did,gas);vm.execute(&self.storage,&self.registry)}pub fn contract_count(&self)->usize{self.registry.count()}}
pub fn build_bytecode(ops:&[(Opcode,Option<u64>)])->Vec<u8>{let mut b=Vec::new();for(op,arg)in ops{b.push(*op as u8);if let Some(v)=arg{b.extend_from_slice(&v.to_be_bytes());}}b}
#[cfg(test)]
mod tests {
    use super::*;
    fn setup() -> VmEngine { VmEngine::new(1_000_000) }
    fn bc(ops: &[(Opcode, Option<u64>)]) -> Vec<u8> { build_bytecode(ops) }
    #[test] fn test_op_from_u8() { assert_eq!(Opcode::from_u8(0x00), Some(Opcode::Nop)); assert_eq!(Opcode::from_u8(0xFF), Some(Opcode::Halt)); assert_eq!(Opcode::from_u8(0x99), None); }
    #[test] fn test_op_gas() { assert_eq!(Opcode::Nop.gas_cost(), 1); assert_eq!(Opcode::Add.gas_cost(), 5); assert_eq!(Opcode::Store.gas_cost(), 5000); }
    #[test] fn test_vm_add() { let e = setup(); let c = bc(&[(Opcode::Push,Some(10)),(Opcode::Push,Some(20)),(Opcode::Add,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),None); assert!(r.success); assert_eq!(r.return_value, 30); }
    #[test] fn test_vm_sub() { let e = setup(); let c = bc(&[(Opcode::Push,Some(50)),(Opcode::Push,Some(20)),(Opcode::Sub,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),None); assert_eq!(r.return_value, 30); }
    #[test] fn test_vm_mul() { let e = setup(); let c = bc(&[(Opcode::Push,Some(7)),(Opcode::Push,Some(6)),(Opcode::Mul,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),None); assert_eq!(r.return_value, 42); }
    #[test] fn test_vm_div() { let e = setup(); let c = bc(&[(Opcode::Push,Some(100)),(Opcode::Push,Some(4)),(Opcode::Div,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),None); assert_eq!(r.return_value, 25); }
    #[test] fn test_vm_div0() { let e = setup(); let c = bc(&[(Opcode::Push,Some(10)),(Opcode::Push,Some(0)),(Opcode::Div,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),None); assert!(!r.success); assert_eq!(r.error, Some(VmError::DivisionByZero)); }
    #[test] fn test_vm_eq() { let e = setup(); let c = bc(&[(Opcode::Push,Some(5)),(Opcode::Push,Some(5)),(Opcode::Eq,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); assert_eq!(e.call("c1","caller".into(),None).return_value, 1); }
    #[test] fn test_vm_lt() { let e = setup(); let c = bc(&[(Opcode::Push,Some(3)),(Opcode::Push,Some(5)),(Opcode::Lt,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); assert_eq!(e.call("c1","caller".into(),None).return_value, 1); }
    #[test] fn test_vm_store_load() { let e = setup(); let c = bc(&[(Opcode::Push,Some(42)),(Opcode::Push,Some(1)),(Opcode::Store,None),(Opcode::Push,Some(1)),(Opcode::Load,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),None); assert_eq!(r.return_value, 42); assert_eq!(e.storage.load("c1", 1), 42); }
    #[test] fn test_vm_gas_track() { let e = setup(); let c = bc(&[(Opcode::Push,Some(1)),(Opcode::Push,Some(2)),(Opcode::Add,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),Some(1000)); assert!(r.gas_used > 0); assert_eq!(r.gas_used + r.gas_refund, 1000); }
    #[test] fn test_vm_oog() { let e = setup(); let c = bc(&[(Opcode::Push,Some(1)),(Opcode::Push,Some(2)),(Opcode::Add,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),Some(5)); assert!(!r.success); assert_eq!(r.error, Some(VmError::OutOfGas)); }
    #[test] fn test_vm_stack_underflow() { let e = setup(); let c = bc(&[(Opcode::Pop,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),None); assert_eq!(r.error, Some(VmError::StackUnderflow)); }
    #[test] fn test_vm_invalid_op() { let e = setup(); e.deploy("c1".into(),vec![0x99],"o".into()); let r = e.call("c1","caller".into(),None); assert_eq!(r.error, Some(VmError::InvalidOpcode(0x99))); }
    #[test] fn test_vm_log() { let e = setup(); let c = bc(&[(Opcode::Push,Some(42)),(Opcode::Push,Some(1)),(Opcode::Log,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),None); assert_eq!(r.logs.len(), 1); assert_eq!(r.logs[0].data[0], 42); }
    #[test] fn test_vm_halt() { let e = setup(); let c = bc(&[(Opcode::Push,Some(42)),(Opcode::Halt,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),None); assert!(r.success); }
    #[test] fn test_vm_empty() { let e = setup(); e.deploy("c1".into(),vec![],"o".into()); let r = e.call("c1","caller".into(),None); assert!(r.success); assert_eq!(r.return_value, 0); }
    #[test] fn test_vm_not_found() { let e = setup(); let r = e.call("nonexist","caller".into(),None); assert!(!r.success); }
    #[test] fn test_vm_factorial() { let e = setup(); let c = bc(&[(Opcode::Push,Some(1)),(Opcode::Push,Some(5)),(Opcode::Mul,None),(Opcode::Push,Some(4)),(Opcode::Mul,None),(Opcode::Push,Some(3)),(Opcode::Mul,None),(Opcode::Push,Some(2)),(Opcode::Mul,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); assert_eq!(e.call("c1","caller".into(),None).return_value, 120); }
    #[test] fn test_vm_self_addr() { let e = setup(); let c = bc(&[(Opcode::Self_,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r = e.call("c1","caller".into(),None); assert!(r.return_value != 0); }
    #[test] fn test_vm_caller() { let e = setup(); let c = bc(&[(Opcode::Caller,None),(Opcode::Ret,None)]); e.deploy("c1".into(),c,"o".into()); let r1 = e.call("c1","alice".into(),None); let r2 = e.call("c1","alice".into(),None); assert_eq!(r1.return_value, r2.return_value); }
}
